---
name: actionlint
env:
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
on:
  pull_request:
    branches: [main]
    paths:
    - .github/**
    - aqua/actionlint.yaml
jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: aquaproj/aqua-installer@v2.1.1
      with:
        aqua_version: v2.3.6
    - uses: suzuki-shunsuke/github-action-actionlint@v0.1.2
