---
name: Release a Terraform Module
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: 'Module path'
        required: true
      version:
        description: 'Module version'
        required: true
permissions:
  contents: write
env:
  TFACTION_TARGET: ${{github.event.inputs.module_path}}
jobs:
  release-module:
    name: "release-module (${{github.event.inputs.module_path}})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.5.2

      - uses: suzuki-shunsuke/tfaction/release-module@971c6b68d49a5ec446cf8d2c2e22793c9c06ac72 # v0.5.23
        with:
          version: ${{ github.event.inputs.version }}
          module_path: ${{ github.event.inputs.module_path }}
