---
name: scaffold tfmigrate
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'target'
        required: true
      migration_name:
        description: 'migration name. e.g. "import_foo"'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TFACTION_TARGET: ${{ github.event.inputs.target }}
permissions:
  contents: read
  pull-requests: write
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.3.6

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: suzuki-shunsuke/tfaction/scaffold-tfmigrate@971c6b68d49a5ec446cf8d2c2e22793c9c06ac72 # v0.5.23
        with:
          github_app_token: ${{ steps.generate_token.outputs.token }}
          migration_name: ${{ github.event.inputs.migration_name }}
