---
name: test
on:
  pull_request:
    # branches: [main]
    branches: [dummy] # Disabled

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/wc-test.yaml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
      terraform_private_module_ssh_key: ${{secrets.TERRAFORM_PRIVATE_MODULE_SSH_KEY}}
      secrets: ${{toJSON(secrets)}}

  # This job is used for branch protection rule
  # Add this job to `Status checks that are required`
  status-check:
    runs-on: ubuntu-latest
    needs:
      - test
    if: failure()
    steps:
      - run: exit 1
